name = "engine-e2e"
engineVersion = "v1.0.0"

[runtime]
source = "dang"

[[dependencies]]
name = "engine-dev"
source = "github.com/dagger/dagger/.dagger/modules/engine-dev@0d031c08ef3e379c6f4eb7f8f5cad4638a168863"
